hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  job_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    - hydra.output_subdir=null
    - hydra.run.dir=.
    - hydra.sweep.dir=.
    - hydra.sweep.subdir=.
    - hydra/job_logging=disabled
    - hydra/hydra_logging=disabled
    task:
    - system.device=-1
    - system.dtype=32
    - seed=1
    - optimizer.use_GN=True
    - optimizer.lr=10.
    - init.pre_train=True
    - init.std=100.
    - optimizer.max_iter=0
    - init.pre_train_iter=1000
    - +mlxp.interactive_mode=True
    - +mlxp.version_manager.parent_work_dir=./data/.workdir
    - +mlxp.logger.parent_log_dir=./data/outputs/figure_2
    - +mlxp.use_version_manager=True
  job:
    name: main
    chdir: null
    override_dirname: +mlxp.interactive_mode=True,+mlxp.logger.parent_log_dir=./data/outputs/figure_2,+mlxp.use_version_manager=True,+mlxp.version_manager.parent_work_dir=./data/.workdir,init.pre_train=True,init.pre_train_iter=1000,init.std=100.,optimizer.lr=10.,optimizer.max_iter=0,optimizer.use_GN=True,seed=1,system.device=-1,system.dtype=32
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/marbel/Documents/projects/Implicit-Bias-Gauss-Newton
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/marbel/Documents/projects/Implicit-Bias-Gauss-Newton/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: disabled
      hydra/hydra_logging: disabled
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
seed: 1
system:
  dtype: 32
  device: -1
model:
  d_int: 10
  H: 5000
  teacher_H: 5
  non_linearity: SiLU
  beta: 1.0
  copy_teacher_network: false
data:
  n_train: 500
  n_test: 10000
metrics:
  dist_freq_eval: 100
  save_freq: 100
optimizer:
  is_linear: false
  lr: 10.0
  use_GN: true
  max_iter: 0
init:
  mean: 0.0
  std: 100.0
  mean_teacher: 0.0
  std_teacher: 1.0
  pre_train: true
  pre_train_iter: 1000
mlxp:
  interactive_mode: true
  version_manager:
    parent_work_dir: ./data/.workdir
  logger:
    parent_log_dir: ./data/outputs/figure_2
  use_version_manager: true
